# Generated by Django 5.2.8 on 2026-01-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_suggestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
    ]
