# Generated by Django 5.2.8 on 2026-01-26 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_suggestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab_suggestion.lab'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='recipient_admin',
            field=models.BooleanField(default=False),
        ),
    ]
