# Generated by Django 5.2.8 on 2026-01-27 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab_suggestion', '0002_contactmessage_lab_contactmessage_recipient_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='popularity',
        ),
    ]
