# Generated by Django 5.2.8 on 2026-01-27 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_suggestion', '0004_airecommendation_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Contact phone number for follow-up', max_length=20, null=True),
        ),
    ]
