# Generated by Django 5.2.8 on 2026-01-23 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_suggestion', '0004_alter_test_description_alter_test_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTestDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_specific_description', models.TextField(blank=True, null=True)),
                ('lab_specific_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_suggestion.lab')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab_suggestion.test')),
            ],
        ),
    ]
