# Generated by Django 5.2.8 on 2026-02-02 03:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_suggestion', '0005_contactmessage_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(db_index=True, default=uuid.uuid4, editable=False, max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('booking_date', models.DateTimeField()),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='booked', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='lab_suggestion.lab')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='lab_suggestion.test')),
            ],
            options={
                'ordering': ['-booked_at'],
                'indexes': [models.Index(fields=['booking_id', 'email'], name='lab_suggest_booking_c1b883_idx'), models.Index(fields=['email'], name='lab_suggest_email_5a559f_idx')],
            },
        ),
    ]
