# Generated by Django 5.2.8 on 2026-01-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_suggestion', '0005_labtestdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='tests',
            field=models.ManyToManyField(blank=True, through='lab_suggestion.LabTestDetail', to='lab_suggestion.test'),
        ),
    ]
