# Generated by Django 5.2.8 on 2026-02-02 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_suggestion', '0006_testbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='testbooking',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the person booking the test', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='testbooking',
            name='booking_id',
            field=models.CharField(db_index=True, editable=False, max_length=50, unique=True),
        ),
    ]
