# Generated by Django 5.2.8 on 2026-02-02 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_suggestion', '0007_testbooking_name_alter_testbooking_booking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testbooking',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('test_done', 'Test Done'), ('not_arrived', 'Not Arrived'), ('cancelled', 'Cancelled')], default='booked', max_length=20),
        ),
    ]
